apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sivacva425/01-k8s-project.git'
    targetRevision: HEAD
    path: 01-k8s-project/helm-charts/web-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
