apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-success-rate
  namespace: default
spec:
  metrics:
  - name: success-rate
    interval: 30s
    successCondition: result >= 0.95
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{status!~"5.*",app=""}[1m])) 
          / 
          sum(rate(http_requests_total{app="ai-devops-backend"}[1m]))
