apiVersion: v1
kind: Service
metadata:
  name: production-web-app-stable
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: production-web-app
---
apiVersion: v1
kind: Service
metadata:
  name: production-web-app-canary
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: production-web-app
